// Generated by apps/web/scripts/generate-contracts.mjs. Do not edit.
// OpenAPI SHA-256: 046b74c7b9575bb27c7d14c5fb977d2855aa59047b7d4507908fd2f4d97b3175
// UI Schema SHA-256: f35fbbf7698eabbbea0b4f971b1e18cd4530148ce6271e7199c36f7411803170

import { z } from "zod";

export type ApiError = {
  "code": string;
  "correlationId": Uuid7;
  "fields": Array<FieldError>;
  "message": string;
};

export type BudgetConstraint = (ConstraintBase) & ({
  "currency": string;
  "id": Slug;
  "kind": "budget";
  "label": string;
  "maximum": number;
  "severity": "hard" | "advisory";
});

export type Capabilities = {
  "canCreateDecision": boolean;
  "canReplayRun": boolean;
  "canResetGuestWorkspace": boolean;
  "canRunDecision": boolean;
  "canUpload": false;
  "canUseGitHub": false;
  "canUseLocalGit": false;
  "canUseWeb": false;
  "persistentWorkspace": boolean;
};

export type CapabilityConstraint = (ConstraintBase) & ({
  "capability": Slug;
  "id": Slug;
  "kind": "capability";
  "label": string;
  "severity": "hard" | "advisory";
});

export type Constraint = (BudgetConstraint) | (DeadlineConstraint) | (CapabilityConstraint) | (ForbiddenVendorConstraint) | (LicenseConstraint) | (ResidencyConstraint) | (DeploymentModeConstraint);

export type ConstraintBase = {
  "id": Slug;
  "kind": string;
  "label": string;
  "severity": "hard" | "advisory";
};

export type CriterionInput = {
  "enteredWeight": EnteredWeight;
  "id": Slug;
  "label": string;
};

export type CriterionView = {
  "enteredWeight": EnteredWeight;
  "id": Slug;
  "label": string;
  "normalizedWeight": NormalizedWeight;
};

export type DeadlineConstraint = (ConstraintBase) & ({
  "date": string;
  "id": Slug;
  "kind": "deadline";
  "label": string;
  "severity": "hard" | "advisory";
});

export type DecisionFrameInput = {
  "constraints": Array<Constraint>;
  "context": string;
  "criteria": Array<CriterionInput>;
  "options": Array<DecisionOption>;
  "question": string;
  "schemaVersion": "1.0";
};

export type DecisionFrameView = {
  "constraints": Array<Constraint>;
  "context": string;
  "criteria": Array<CriterionView>;
  "options": Array<DecisionOption>;
  "question": string;
  "schemaVersion": "1.0";
};

export type DecisionOption = {
  "description": string;
  "id": Slug;
  "label": string;
};

export type DecisionView = {
  "createdAt": string;
  "currentRevision": number;
  "frame": DecisionFrameView;
  "id": Uuid7;
  "updatedAt": string;
};

export type DeploymentModeConstraint = (ConstraintBase) & ({
  "allowedModes": Array<"managed" | "self-hosted" | "on-device">;
  "id": Slug;
  "kind": "deployment-mode";
  "label": string;
  "severity": "hard" | "advisory";
});

export type EnteredWeight = string;

export type FieldError = {
  "code": string;
  "path": string;
};

export type ForbiddenVendorConstraint = (ConstraintBase) & ({
  "id": Slug;
  "kind": "forbidden-vendor";
  "label": string;
  "severity": "hard" | "advisory";
  "vendor": string;
});

export type LicenseConstraint = (ConstraintBase) & ({
  "allowedSpdx": Array<string>;
  "id": Slug;
  "kind": "license";
  "label": string;
  "severity": "hard" | "advisory";
});

export type Liveness = {
  "status": "live";
};

export type NormalizedWeight = string;

export type OptionScore = {
  "optionId": Slug;
  "score": number;
};

export type Readiness = {
  "checks": {
    "migrations": "ready" | "not-ready";
    "postgres": "ready" | "not-ready";
    "qdrant": "ready" | "not-ready";
    [key: string]: "ready" | "not-ready";
  };
  "status": "ready" | "not-ready";
};

export type RecommendationSummary = {
  "disclaimer": string;
  "id": Slug;
  "kind": "recommendation-summary";
  "optionScores": Array<OptionScore>;
  "rationale": string;
  "selectedOptionId": Slug;
  "status": "demonstration";
  "title": string;
};

export type ResetSessionResponse = {
  "guestExpiresAt": string;
  "resetAccepted": true;
};

export type ResidencyConstraint = (ConstraintBase) & ({
  "allowedCountries": Array<string>;
  "id": Slug;
  "kind": "residency";
  "label": string;
  "severity": "hard" | "advisory";
});

export type RunCompletedEvent = (RunEventBase) & ({
  "kind"?: "run.completed";
  "payload"?: RunCompletedPayload;
});

export type RunCompletedPayload = {
  "status": "completed";
};

export type RunEvent = (RunQueuedEvent) | (RunStartedEvent) | (UiEnvelopeEvent) | (RunCompletedEvent) | (RunFailedEvent);

export type RunEventBase = {
  "createdAt": string;
  "kind": "run.queued" | "run.started" | "ui.envelope" | "run.completed" | "run.failed";
  "payload": {
    [key: string]: unknown;
  };
  "runId": Uuid7;
  "schemaVersion": "1.0";
  "sequence": number;
};

export type RunFailedEvent = (RunEventBase) & ({
  "kind"?: "run.failed";
  "payload"?: RunFailurePayload;
});

export type RunFailurePayload = {
  "errorCode": string;
  "status": "failed";
};

export type RunQueuedEvent = (RunEventBase) & ({
  "kind"?: "run.queued";
  "payload"?: RunQueuedPayload;
});

export type RunQueuedPayload = {
  "status": "queued";
};

export type RunStartedEvent = (RunEventBase) & ({
  "kind"?: "run.started";
  "payload"?: RunStartedPayload;
});

export type RunStartedPayload = {
  "status": "running";
};

export type RuntimeConfig = {
  "apiVersion": "v1";
  "capabilities": Capabilities;
  "guestExpiresAt": (string) | (null);
  "mode": "public-demo" | "local-data";
};

export type RunView = {
  "completedAt": (string) | (null);
  "createdAt": string;
  "decisionId": Uuid7;
  "decisionRevision": number;
  "errorCode": (string) | (null);
  "fixtureVersion": "walking-skeleton-v1";
  "id": Uuid7;
  "lastEventSequence": number;
  "startedAt": (string) | (null);
  "status": "queued" | "running" | "completed" | "failed";
};

export type Slug = string;

export type UiEnvelope = {
  "actions": Array<ViewEvidenceAction>;
  "component": RecommendationSummary;
  "meta": UiEnvelopeMeta;
  "schemaVersion": "1.0";
};

export type UiEnvelopeEvent = (RunEventBase) & ({
  "kind"?: "ui.envelope";
  "payload"?: UiEnvelope;
});

export type UiEnvelopeMeta = {
  "eventSequence": number;
  "fixtureVersion": "walking-skeleton-v1";
  "generatedBy": "deterministic-fixture";
  "runId": Uuid7;
};

export type Uuid7 = string;

export type ViewEvidenceAction = {
  "enabled": false;
  "id": Slug;
  "kind": "view-evidence";
  "label": string;
};

function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map(canonicalJson).join(",")}]`;
  }
  if (value !== null && typeof value === "object") {
    const record = value as Record<string, unknown>;
    const entries = Object.keys(record)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonicalJson(record[key])}`);
    return `{${entries.join(",")}}`;
  }
  return JSON.stringify(value) ?? "undefined";
}

export function hasDuplicateJsonValues(values: readonly unknown[]): boolean {
  const identities = values.map(canonicalJson);
  return new Set(identities).size !== identities.length;
}

const envelopeMetaSchema = z.object({
  "eventSequence": z.number().finite().int().min(1),
  "fixtureVersion": z.literal("walking-skeleton-v1"),
  "generatedBy": z.literal("deterministic-fixture"),
  "runId": z.string().uuid().regex(new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"))
}).strict();

const optionScoreSchema = z.object({
  "optionId": z.string().regex(new RegExp("^[a-z0-9]+(?:-[a-z0-9]+)*$")).refine((value) => Array.from(value).length >= 1, "string is too short").refine((value) => Array.from(value).length <= 64, "string is too long"),
  "score": z.number().finite().min(0).max(100)
}).strict();

const recommendationSummarySchema = z.object({
  "disclaimer": z.string().refine((value) => Array.from(value).length >= 1, "string is too short").refine((value) => Array.from(value).length <= 240, "string is too long"),
  "id": z.string().regex(new RegExp("^[a-z0-9]+(?:-[a-z0-9]+)*$")).refine((value) => Array.from(value).length >= 1, "string is too short").refine((value) => Array.from(value).length <= 64, "string is too long"),
  "kind": z.literal("recommendation-summary"),
  "optionScores": z.array(optionScoreSchema).min(2).max(8).superRefine((items, context) => { if (hasDuplicateJsonValues(items)) { context.addIssue({ code: z.ZodIssueCode.custom, message: "array items must be unique" }); } }),
  "rationale": z.string().refine((value) => Array.from(value).length >= 1, "string is too short").refine((value) => Array.from(value).length <= 1200, "string is too long"),
  "selectedOptionId": z.string().regex(new RegExp("^[a-z0-9]+(?:-[a-z0-9]+)*$")).refine((value) => Array.from(value).length >= 1, "string is too short").refine((value) => Array.from(value).length <= 64, "string is too long"),
  "status": z.literal("demonstration"),
  "title": z.string().refine((value) => Array.from(value).length >= 1, "string is too short").refine((value) => Array.from(value).length <= 160, "string is too long")
}).strict();

const viewEvidenceActionSchema = z.object({
  "enabled": z.literal(false),
  "id": z.string().regex(new RegExp("^[a-z0-9]+(?:-[a-z0-9]+)*$")).refine((value) => Array.from(value).length >= 1, "string is too short").refine((value) => Array.from(value).length <= 64, "string is too long"),
  "kind": z.literal("view-evidence"),
  "label": z.string().refine((value) => Array.from(value).length >= 1, "string is too short").refine((value) => Array.from(value).length <= 80, "string is too long")
}).strict();

export const uiEnvelopeSchema = z.object({
  "actions": z.array(viewEvidenceActionSchema).max(1),
  "component": recommendationSummarySchema,
  "meta": envelopeMetaSchema,
  "schemaVersion": z.literal("1.0")
}).strict();

export type UiEnvelopeRuntime = z.infer<typeof uiEnvelopeSchema>;
